In [1]:
import zipfile

# unzip the files so that you can see them..
with zipfile.ZipFile("/kaggle/input/aerial-cactus-identification/train.zip","r") as z:
    z.extractall("/kaggle/working/train")
with zipfile.ZipFile("/kaggle/input/aerial-cactus-identification/test.zip","r") as z:
    z.extractall("/kaggle/working/test")

In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from IPython.display import Image
from keras.preprocessing import image
from keras.preprocessing.image import ImageDataGenerator
from keras import optimizers
from keras import regularizers
from keras import layers,models
from keras.layers.core import Dense
from keras.layers import Conv2D, MaxPool2D, Flatten

import matplotlib.pyplot as plt

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import cv2
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

2026-01-07 06:20:31.635288: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1767766831.648467      10 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1767766831.652613      10 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-01-07 06:20:31.669242: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

ImportError: cannot import name 'ImageDataGenerator' from 'keras.preprocessing.image' (/usr/local/lib/python3.11/dist-packages/keras/api/preprocessing/image/__init__.py)

In [3]:
train_directory = "/kaggle/working/train/train"
test_directory = "/kaggle/working/test/"

In [4]:
train_df = pd.read_csv('../input/aerial-cactus-identification/train.csv',dtype=str) # "dtype=str" is importend for the later flow_from_dataframe-method
train_df

                                         id has_cactus
0      2de8f189f1dce439766637e75df0ee27.jpg          1
1      36704d250f236238e7f996812c48235d.jpg          1
2      eacde22fdc8c175972a5768e3daa8bc9.jpg          1
3      5d442f834da5e57d22b24802c32a8ca8.jpg          1
4      152491e0daf75c0e669400300ff7e645.jpg          1
...                                     ...        ...
14170  84e954e51ed7cfc3702759eda634585d.jpg          1
14171  be775ee33a72c05e44d3f94dfc1d064d.jpg          1
14172  8d8d6a9befed07acf7eee92714c548e3.jpg          1
14173  9c0088be4e9e91be0f5533ea9c521778.jpg          1
14174  2654166bc65ed53655b41c70217a8cdc.jpg          0

[14175 rows x 2 columns]

In [5]:
test_df = pd.read_csv('../input/aerial-cactus-identification/sample_submission.csv',dtype=str) # "dtype=str" is importend for the later flow_from_dataframe-method
test_df

                                        id has_cactus
0     09034a34de0e2015a8a28dfe18f423f6.jpg        0.5
1     134f04305c795d6d202502c2ce3578f3.jpg        0.5
2     41fad8d145e6c41868ce3617e30a2545.jpg        0.5
3     35f8a11352c8d41b6231bb33d8d09f7e.jpg        0.5
4     b77dc902b035887cbbc01920ce0e3151.jpg        0.5
...                                    ...        ...
3320  30aefb527376be40a5530b9f78010a00.jpg        0.5
3321  8a55f8ee366475c494c6144fca8eacff.jpg        0.5
3322  83aa00121a789c654ec78e2e9639cdcb.jpg        0.5
3323  2246209a6d93a68be1dbf1fcd66e78ab.jpg        0.5
3324  d81b2399e7505f728516d5c78010e95a.jpg        0.5

[3325 rows x 2 columns]

In [6]:
#have a look at the first image in train-directory
import cv2
Image(os.path.join("/kaggle/working/train/train",train_df.iloc[0,0]),width=32,height=32)

NameError: name 'os' is not defined

In [7]:
# using the ImageDataGenerator-class from keras for preparing the data
main_datagenerator=ImageDataGenerator(rescale=1./255)

NameError: name 'ImageDataGenerator' is not defined

In [8]:
# store all image-data from the train directory in an ImageDataGenerator
# the data-generator produces packages of 150x(images,label) with shape (150,32,32,3)
# the 'has_cactus'-entries come from the train_df
# the images come from the train_directory
# splitting them into train- and validation-data
train_data_batch_size=150
train_datagenerator = main_datagenerator.flow_from_dataframe(dataframe=train_df[:15001],directory=train_directory,x_col="id",y_col="has_cactus",class_mode='binary',target_size=(32,32),batch_size=train_data_batch_size)
val_data_batch_size=20
val_datagenerator = main_datagenerator.flow_from_dataframe(dataframe=train_df[15000:],directory=train_directory,x_col="id",y_col="has_cactus",class_mode='binary',target_size=(32,32),batch_size=val_data_batch_size)

NameError: name 'main_datagenerator' is not defined

In [9]:
# take a look at the generator-outputs
for data, labels in train_datagenerator:
    print("data-shape: ",data.shape)
    print("label-shape: ",labels.shape)
    break # dont want to see the hole generating shapes

NameError: name 'train_datagenerator' is not defined

In [10]:
model=models.Sequential()
# first the CNN
model.add(Conv2D(32,(3,3),padding='same',activation='relu',input_shape=(32,32,3)))
model.add(MaxPool2D((2,2)))
model.add(Conv2D(64,(3,3),padding='same',activation='relu',input_shape=(32,32,3)))
model.add(MaxPool2D((2,2)))
model.add(Conv2D(128,(3,3),padding='same',activation='relu',input_shape=(32,32,3)))
model.add(MaxPool2D((2,2)))
model.add(Conv2D(128,(3,3),padding='same',activation='relu',input_shape=(32,32,3)))
model.add(MaxPool2D((2,2)))
# following by an MLP
model.add(Flatten())
model.add(Dense(512,activation='relu'))
model.add(Dense(128,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

#model.add(Dense(512, kernel_regularizer=regularizers.l2(0.001),activity_regularizer=regularizers.l2(0.001),activation='relu'))
#model.add(Dense(1, activation='sigmoid'))







model.summary()

NameError: name 'models' is not defined

In [11]:
model.compile(loss='binary_crossentropy',optimizer=optimizers.rmsprop(lr=1e-4),metrics=['acc'])

NameError: name 'model' is not defined

In [12]:
number_of_epochs = 10 #50
steps = 30          #100

history=model.fit_generator(
    train_datagenerator,
    steps_per_epoch=steps,
    epochs=number_of_epochs,
    validation_data=val_datagenerator,
    validation_steps=20,
    verbose=1)

NameError: name 'model' is not defined

In [13]:
# Plot training & validation accuracy values
plt.plot(history.history['acc'])
plt.plot(history.history['val_acc'])
plt.title('Model accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train', 'Test'], loc='upper left')
plt.show()

NameError: name 'plt' is not defined

In [14]:
# Plot training & validation loss values
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Model loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train', 'Test'], loc='upper left')
plt.show()

NameError: name 'plt' is not defined

In [15]:
# creating a ImageDataGenerator with one-single-image-per-batch an no shuffle

test_generator = main_datagenerator.flow_from_directory(
    directory=test_directory,
    target_size=(32,32),
    batch_size=1,# no packages
    class_mode='binary',
    shuffle=False # maintain the sequence
)

NameError: name 'main_datagenerator' is not defined

In [16]:
prediction=model.predict_generator(test_generator,verbose=1)
pred_binary = [0 if value<0.50 else 1 for value in prediction] 
pred_binary = np.array(pred_binary)
pred_binary.reshape(4000,1)
print(pred_binary)
import collections
collections.Counter(pred_binary)

NameError: name 'model' is not defined

In [17]:
# get the test-images as a list of '*.jpg-name'-strings from the test directory
test_files = test_df['id'] # os.listdir("/kaggle/working/test/test")
test_files

0       09034a34de0e2015a8a28dfe18f423f6.jpg
1       134f04305c795d6d202502c2ce3578f3.jpg
2       41fad8d145e6c41868ce3617e30a2545.jpg
3       35f8a11352c8d41b6231bb33d8d09f7e.jpg
4       b77dc902b035887cbbc01920ce0e3151.jpg
                        ...
3320    30aefb527376be40a5530b9f78010a00.jpg
3321    8a55f8ee366475c494c6144fca8eacff.jpg
3322    83aa00121a789c654ec78e2e9639cdcb.jpg
3323    2246209a6d93a68be1dbf1fcd66e78ab.jpg
3324    d81b2399e7505f728516d5c78010e95a.jpg
Name: id, Length: 3325, dtype: object

In [18]:
# constructing the dataframe (2 columns with entries 'id *.jpg-name' '0/1 has cactus')
sub_file = pd.DataFrame(data = {'id': test_files, 'has_cactus': pred_binary.reshape(-1).tolist()})
sub_file

NameError: name 'pred_binary' is not defined

In [19]:
import shutil
shutil.rmtree('/kaggle/working/test')
shutil.rmtree('/kaggle/working/train')

In [20]:
#produce the submission file
sub_file.to_csv('submission.csv', index=False)

NameError: name 'sub_file' is not defined