In [1]:
import os
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import math

import keras
from keras.models import Sequential
from keras.layers import *
from keras_preprocessing.image import ImageDataGenerator

import zipfile

2026-01-07 06:54:27.691678: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1767768867.704716      11 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1767768867.708685      11 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-01-07 06:54:27.724593: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

ModuleNotFoundError: No module named 'keras_preprocessing'

In [2]:
train_data = pd.read_csv("../input/aerial-cactus-identification/train.csv", dtype=str)
test_data = pd.read_csv("../input/aerial-cactus-identification/sample_submission.csv", dtype=str)

In [3]:
train_data.head()

                                     id has_cactus
0  2de8f189f1dce439766637e75df0ee27.jpg          1
1  36704d250f236238e7f996812c48235d.jpg          1
2  eacde22fdc8c175972a5768e3daa8bc9.jpg          1
3  5d442f834da5e57d22b24802c32a8ca8.jpg          1
4  152491e0daf75c0e669400300ff7e645.jpg          1

In [4]:
train_data.describe()

                                          id has_cactus
count                                  14175      14175
unique                                 14175          2
top     2de8f189f1dce439766637e75df0ee27.jpg          1
freq                                       1      10628

In [5]:
test_data.describe()

                                          id has_cactus
count                                   3325       3325
unique                                  3325          1
top     09034a34de0e2015a8a28dfe18f423f6.jpg        0.5
freq                                       1       3325

In [6]:
zip_ref_1 = zipfile.ZipFile('/kaggle/input/aerial-cactus-identification/test.zip')
zip_ref_1.extractall()

NameError: name 'zipfile' is not defined

In [7]:
zip_ref_2 = zipfile.ZipFile('/kaggle/input/aerial-cactus-identification/train.zip')
zip_ref_2.extractall()

NameError: name 'zipfile' is not defined

In [8]:
train_path = "train/"
test_path = "test/"
print('Training Images:', len(os.listdir(train_path)))
print('Testing Images: ', len(os.listdir(test_path)))

FileNotFoundError: [Errno 2] No such file or directory: 'train/'

In [9]:
train_datagen = ImageDataGenerator(rescale= 1/255, validation_split = 0.20)
test_datagen = ImageDataGenerator(rescale = 1/255)

NameError: name 'ImageDataGenerator' is not defined

In [10]:
bs = 100

train_generator = train_datagen.flow_from_dataframe(
    dataframe = train_data,
    directory = train_path,
    x_col = "id",
    y_col = "has_cactus",
    subset = "training",
    batch_size = bs,
    shuffle = True,
    class_mode = "categorical",
    target_size = (32,32))

valid_generator = train_datagen.flow_from_dataframe(
    dataframe = train_data,
    directory = train_path,
    x_col = "id",
    y_col = "has_cactus",
    subset = "validation",
    batch_size = bs,
    shuffle = True,
    class_mode = "categorical",
    target_size = (32,32))

test_generator = test_datagen.flow_from_dataframe(
    dataframe = test_data,
    directory = test_path,
    x_col = "id",
    y_col = None,
    batch_size = bs,
    seed = 1,
    shuffle = False,
    class_mode = None,
    target_size = (32,32))

NameError: name 'train_datagen' is not defined

In [11]:
tr_size = 14000
va_size = 3500
te_size = 4000
tr_steps = math.ceil(tr_size/bs)
va_steps = math.ceil(va_size/bs)
te_steps = math.ceil(te_size/bs)

In [12]:
cnn = Sequential()

cnn.add(Conv2D(28, (3,3), activation = 'relu', padding = 'same', input_shape = (32,32,3)))
cnn.add(Conv2D(28, (3,3), activation = 'relu', padding = 'same'))
cnn.add(MaxPooling2D(2,2))
cnn.add(BatchNormalization())

cnn.add(Conv2D(56, (3,3), activation = 'relu', padding = 'same'))
cnn.add(Conv2D(56, (3,3), activation = 'relu', padding = 'same'))
cnn.add(MaxPooling2D(2,2))
cnn.add(BatchNormalization())

cnn.add(Flatten())
cnn.add(Dense(128, activation = 'relu'))
cnn.add(BatchNormalization())

cnn.add(Dense(2, activation = "softmax"))

cnn.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
2026-01-07 06:54:34.150927: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
I0000 00:00:1767768874.151401      11 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 46866 MB memory:  -> device: 0, name: NVIDIA RTX A6000, pci bus id: 0000:86:00.0, compute capability: 8.6

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 32, 32, 28)     │           784 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 32, 32, 28)     │         7,084 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 16, 16, 28)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 16, 16, 28)     │           112 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 16, 16, 56)     │        14,168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 16, 16, 56)     │        28,280 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 8, 8, 56)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 8, 8, 56)       │           224 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 3584)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 128)            │       458,880 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_2           │ (None, 128)            │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 2)              │           258 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 510,302 (1.95 MB)

 Trainable params: 509,878 (1.95 MB)

 Non-trainable params: 424 (1.66 KB)

In [13]:
opt = keras.optimizers.Adam(0.001)
cnn.compile(loss = 'categorical_crossentropy', optimizer = opt, metrics = ['accuracy'])

h1 = cnn.fit_generator(train_generator, steps_per_epoch = tr_steps, epochs=80, validation_data = valid_generator, validation_steps=va_steps, verbose=1)

AttributeError: 'Sequential' object has no attribute 'fit_generator'

In [14]:
start = 1
ep_rng = np.arange(start,len(h1.history['accuracy']))

plt.figure(figsize = [12,6])
plt.subplot(1,2,1)
plt.plot(ep_rng, h1.history['accuracy'][start:], label = 'Training Accuracy')
plt.plot(ep_rng, h1.history['val_accuracy'][start:], label = 'Validation Accuracy')
plt.xlabel('Epoch')
plt.legend()

plt.subplot(1,2,2)
plt.plot(ep_rng, h1.history['loss'][start:], label = 'Training Loss')
plt.plot(ep_rng, h1.history['val_loss'][start:], label = 'Validation Loss')
plt.xlabel('Epoch')
plt.legend()

plt.show()

NameError: name 'h1' is not defined

In [15]:
test_pred = cnn.predict_generator(test_generator, steps=te_steps, verbose=1)

AttributeError: 'Sequential' object has no attribute 'predict_generator'

In [16]:
test_fnames = test_generator.filenames
pred_classes = np.argmax(test_pred, axis=1)

print(np.sum(pred_classes == 0))
print(np.sum(pred_classes == 1))

NameError: name 'test_generator' is not defined

In [17]:
submission = pd.DataFrame({
    'id':test_fnames,
    'has_cactus':pred_classes
})

submission.to_csv('submission.csv', index=False)

submission.head()

NameError: name 'test_fnames' is not defined

In [18]:
import shutil

shutil.rmtree('/kaggle/working/train')
shutil.rmtree('/kaggle/working/test')

FileNotFoundError: [Errno 2] No such file or directory: '/kaggle/working/train'