In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os

import zipfile

# import cv2 
from PIL import Image
# from PIL import ImageShow

# from IPython.display import display
from sklearn.preprocessing import LabelEncoder # LabelBinarizer

# import tensorflow packages
import tensorflow as tf
# from tensorflow.keras.applications.vgg19 import preprocess_input
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Conv2D, MaxPool2D, Dense, BatchNormalization, Dropout,Flatten, Input

from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping

import tensorflow_addons as tfa
from tensorflow_addons.metrics import F1Score
# import tensorflow_datasets as tfds

2026-01-07 06:32:25.498800: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1767767545.512714      12 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1767767545.517003      12 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-01-07 06:32:25.535315: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

ModuleNotFoundError: No module named 'tensorflow_addons'

In [2]:
y_train = pd.read_csv('/kaggle/input/plant-pathology-2021-fgvc8/train.csv')

In [3]:
file_path_test = '/kaggle/input/plant-pathology-2021-fgvc8/test_images'
test_filenames = os.listdir(file_path_test)

In [4]:
sumb_sample = pd.read_csv('../input/plant-pathology-2021-fgvc8/sample_submission.csv')
sumb_sample

                     image   labels
0     ca6a50c5d2adb8ae.jpg  healthy
1     b686d217a1e2e3a5.jpg  healthy
2     c9a5345ec78b4ac5.jpg  healthy
3     acdc8d88549873d7.jpg  healthy
4     cf7d6b1e5856a021.jpg  healthy
...                    ...      ...
3722  a078976b5f86f1c0.jpg  healthy
3723  c8c265728b956f95.jpg  healthy
3724  ad6eda34fca230c1.jpg  healthy
3725  fe0d8008d4ffc09f.jpg  healthy
3726  ba0be0be4f7d05a0.jpg  healthy

[3727 rows x 2 columns]

In [5]:
subm = [(item, 'rust') for item in test_filenames]
subm

[('df98c83c4d383c2d.jpg', 'rust'),
 ('817e97dad0c33ae0.jpg', 'rust'),
 ('e984c49aef3d54a1.jpg', 'rust'),
 ('8cf2ee38c423d837.jpg', 'rust'),
 ('e5319c4b1ce90d5e.jpg', 'rust'),
 ('f24ec79648c39687.jpg', 'rust'),
 ('c5c606c3cfe3e2e0.jpg', 'rust'),
 ('a0b01bcf6c3c9df0.jpg', 'rust'),
 ('a96b827e5ee4a425.jpg', 'rust'),
 ('b4a89ec89ababc15.jpg', 'rust'),
 ('dd5f559b8aa06170.jpg', 'rust'),
 ('f5ac98eaa9a5601b.jpg', 'rust'),
 ('acdb869c106d7a47.jpg', 'rust'),
 ('a53ad564ad6aa50e.jpg', 'rust'),
 ('e38f131b6383b48b.jpg', 'rust'),
 ('c96f37f88c4c26c1.jpg', 'rust'),
 ('d0e491f459626cbb.jpg', 'rust'),
 ('d246b1c6e06f40bf.jpg', 'rust'),
 ('9462726f63dec438.jpg', 'rust'),
 ('f53997d34c8e302c.jpg', 'rust'),
 ('a0c6d0d49cdf1e5a.jpg', 'rust'),
 ('a5a9eac6565854b5.jpg', 'rust'),
 ('fc76db83488e223c.jpg', 'rust'),
 ('c5a137f13683cb46.jpg', 'rust'),
 ('89afbce1e20f8296.jpg', 'rust'),
 ('a59a5a949bead191.jpg', 'rust'),
 ('a0d0dadf0f266a72.jpg', 'rust'),
 ('9dfc3532f494c0cc.jpg', 'rust'),
 ('933951f9db800ab7.jpg', 'rust'),
 ('e1afdf604b2ea2c0.jpg', 'rust'),
 ('ff5ed0bfc004cd04.jpg', 'rust'),
 ('838183cd39b95b7a.jpg', 'rust'),
 ('beb4618f31d86645.jpg', 'rust'),
 ('c39b006c6774a767.jpg', 'rust'),
 ('a7eefea553092148.jpg', 'rust'),
 ('eab5be9280c3a8cb.jpg', 'rust'),
 ('93d372ea6b94285c.jpg', 'rust'),
 ('859d3ac6e0bc4fa1.jpg', 'rust'),
 ('f20aa5a5afa28a97.jpg', 'rust'),
 ('e09617da6991cf49.jpg', 'rust'),
 ('c198cf2f7a1f850a.jpg', 'rust'),
 ('a8469cafcc95cda1.jpg', 'rust'),
 ('a38e8c91f451b65e.jpg', 'rust'),
 ('90693d3fa578d04d.jpg', 'rust'),
 ('dafc78c530769170.jpg', 'rust'),
 ('cc8f1dd8ea243b0e.jpg', 'rust'),
 ('8aff306a89259d66.jpg', 'rust'),
 ('95e8add0d2ba6f20.jpg', 'rust'),
 ('f88b97d202faa790.jpg', 'rust'),
 ('ae7a84319e8f5187.jpg', 'rust'),
 ('b815e17ac747078b.jpg', 'rust'),
 ('d840fd8552de07bc.jpg', 'rust'),
 ('87818c3239fff1c8.jpg', 'rust'),
 ('84c2b48da27b8cf7.jpg', 'rust'),
 ('9c744e8e2796433e.jpg', 'rust'),
 ('c9d1f0330bbdc4e1.jpg', 'rust'),
 ('b124c91bec5b5f14.jpg', 'rust'),
 ('ca802fffe87a1503.jpg', 'rust'),
 ('da88e0b89ded7c06.jpg', 'rust'),
 ('935b9982bcc57cb0.jpg', 'rust'),
 ('b298d1d374552f86.jpg', 'rust'),
 ('eeca70a9a115563b.jpg', 'rust'),
 ('99ae3b3272f26151.jpg', 'rust'),
 ('ee15c6709acf08ce.jpg', 'rust'),
 ('8a9138ebc3a68f8d.jpg', 'rust'),
 ('d36d368832c31c7b.jpg', 'rust'),
 ('c4212c57fe4273ec.jpg', 'rust'),
 ('9792cb5b859d448d.jpg', 'rust'),
 ('c8e373317ae003dd.jpg', 'rust'),
 ('83b51f60f8c5f8c2.jpg', 'rust'),
 ('b170602f6fcd9919.jpg', 'rust'),
 ('a55235c3d735a7c0.jpg', 'rust'),
 ('f8adc5153e9238e1.jpg', 'rust'),
 ('b407d2af9b809f52.jpg', 'rust'),
 ('b0a180da5f6e7a65.jpg', 'rust'),
 ('e5ad94471d9e4c51.jpg', 'rust'),
 ('afb7f05e80f4032a.jpg', 'rust'),
 ('e58390afc33c3fa0.jpg', 'rust'),
 ('efd0606bca648375.jpg', 'rust'),
 ('c47a6ed8a111175f.jpg', 'rust'),
 ('c3eac5fdc8343a11.jpg', 'rust'),
 ('9507976774e01d1d.jpg', 'rust'),
 ('d2b41f53696d2c4a.jpg', 'rust'),
 ('85b90c94badad92d.jpg', 'rust'),
 ('eb3ce0f040f20bde.jpg', 'rust'),
 ('bfc0d64ec823e638.jpg', 'rust'),
 ('c3897fdde0e8e0c0.jpg', 'rust'),
 ('d2ae6e882498e4fb.jpg', 'rust'),
 ('c3343716d65a5a66.jpg', 'rust'),
 ('9e31c0cbdc54d4b5.jpg', 'rust'),
 ('b8b0ee5bb4058f1a.jpg', 'rust'),
 ('e82fd16492b333b2.jpg', 'rust'),
 ('e9f9a450d5d80799.jpg', 'rust'),
 ('b03770fa364bc12d.jpg', 'rust'),
 ('aa2f5af05b00b9cd.jpg', 'rust'),
 ('dc9c540c6ceda387.jpg', 'rust'),
 ('97f370b0d8d36078.jpg', 'rust'),
 ('fcd8e8123c5360cf.jpg', 'rust'),
 ('d5c328d3439e83a7.jpg', 'rust'),
 ('e8ff95c0c2619cc5.jpg', 'rust'),
 ('adc483b3eab562a1.jpg', 'rust'),
 ('f4328feb81c883ad.jpg', 'rust'),
 ('8c9f80e15a36e97a.jpg', 'rust'),
 ('99c5c1e959378933.jpg', 'rust'),
 ('dfa488878aef88e4.jpg', 'rust'),
 ('e9a7cebcc41840bd.jpg', 'rust'),
 ('bd68c9c4ef090c1f.jpg', 'rust'),
 ('b2a2b59f8d6d1017.jpg', 'rust'),
 ('cdd8c0f404bacbbc.jpg', 'rust'),
 ('95e922d99bcba431.jpg', 'rust'),
 ('937781c0768365be.jpg', 'rust'),
 ('9192cdf1898afaaa.jpg', 'rust'),
 ('87e53a22ef6151b8.jpg', 'rust'),
 ('f8e547464ede9604.jpg', 'rust'),
 ('cd10d6dfdb9a880a.jpg', 'rust'),
 ('fb31d0020bef3e4c.jpg', 'rust'),
 ('c3a2b8eff8e06093.jpg', 'rust'),
 ('a37bd4a0d8d67648.jpg', 'rust'),
 ('f2188d6318c66bee.jpg', 'rust'),
 ('b4d3cb9d5d586822.jpg', 'rust'),
 ('90d26aeb2a2f8d2b.jpg', 'rust'),
 ('fc7fd461eac15500.jpg', 'rust'),
 ('ceee14f9db12c290.jpg', 'rust'),
 ('a52d9435d2769974.jpg', 'rust'),
 ('c4e51ee01d484dfb.jpg', 'rust'),
 ('90f99ee1c1132bb6.jpg', 'rust'),
 ('d60160cf9d37c63c.jpg', 'rust'),
 ('8ed47a5ca47c096d.jpg', 'rust'),
 ('e0f242706143e7fd.jpg', 'rust'),
 ('977b0ac19c1f50d9.jpg', 'rust'),
 ('ea675274ca82ac9b.jpg', 'rust'),
 ('d4b9cbf09c3f8026.jpg', 'rust'),
 ('b612c8ee354a7335.jpg', 'rust'),
 ('bcb2c0d28ecb8d87.jpg', 'rust'),
 ('e8bd8ac4d982dd83.jpg', 'rust'),
 ('e08ecf1957938ca3.jpg', 'rust'),
 ('83c33e1d37c8b748.jpg', 'rust'),
 ('b0e141ea1ab267de.jpg', 'rust'),
 ('d72482b49f346ad6.jpg', 'rust'),
 ('b56ac2d18d97da24.jpg', 'rust'),
 ('e08c00bf919a3fd7.jpg', 'rust'),
 ('b9ea9bc11be42e28.jpg', 'rust'),
 ('98bdda1a89150fd5.jpg', 'rust'),
 ('cab398d7c8946ca3.jpg', 'rust'),
 ('e1a61cf6e982628f.jpg', 'rust'),
 ('df8d975806fd4111.jpg', 'rust'),
 ('c3ca9a4aa4e0eed6.jpg', 'rust'),
 ('f0b6b692caa0f11e.jpg', 'rust'),
 ('bd87e086a083fd2b.jpg', 'rust'),
 ('e1bd81a46d56e45a.jpg', 'rust'),
 ('eea09f90979490de.jpg', 'rust'),
 ('a081d4e09f0b9efe.jpg', 'rust'),
 ('aa57ad93d405c05f.jpg', 'rust'),
 ('c8e822eb7e127536.jpg', 'rust'),
 ('b918d330cfd1e760.jpg', 'rust'),
 ('81f5730f2b1c3731.jpg', 'rust'),
 ('b53b8733d03658d2.jpg', 'rust'),
 ('9fd12addd42ac28a.jpg', 'rust'),
 ('af1232bbf01a43b9.jpg', 'rust'),
 ('d2d4948d7c68e4f2.jpg', 'rust'),
 ('9a6435c665b4c23f.jpg', 'rust'),
 ('f0acf138b7a3a905.jpg', 'rust'),
 ('81ad1d4bed8b20fa.jpg', 'rust'),
 ('826c96e83790799f.jpg', 'rust'),
 ('f99bd07118e01f3c.jpg', 'rust'),
 ('b00ed005cdf636db.jpg', 'rust'),
 ('df20c87bf42529c9.jpg', 'rust'),
 ('e1b2930796cfb2a8.jpg', 'rust'),
 ('f2ac8c0f4ea805fb.jpg', 'rust'),
 ('aff81e8251c06bbc.jpg', 'rust'),
 ('e0ad17c4f2a302bf.jpg', 'rust'),
 ('e59797c24276026f.jpg', 'rust'),
 ('c9c738261ff047f0.jpg', 'rust'),
 ('f4b99bd1592c2564.jpg', 'rust'),
 ('9894ad9bae345365.jpg', 'rust'),
 ('aea7585af8e1c047.jpg', 'rust'),
 ('a39bd3c311438f3c.jpg', 'rust'),
 ('94a873d2895adda5.jpg', 'rust'),
 ('ad72d9a0c0b74b95.jpg', 'rust'),
 ('cae2680ea2abebac.jpg', 'rust'),
 ('a5c096e9d0699f66.jpg', 'rust'),
 ('a3c07f627343c89d.jpg', 'rust'),
 ('a18ce35a48be5fd0.jpg', 'rust'),
 ('caac79d13704ecca.jpg', 'rust'),
 ('e92d0dd552a79436.jpg', 'rust'),
 ('ed96969ad6954a41.jpg', 'rust'),
 ('b8572f41970fe0f0.jpg', 'rust'),
 ('b512da6d657c32c4.jpg', 'rust'),
 ('ca62f80f2f42dcf0.jpg', 'rust'),
 ('91d0d07cf06747ad.jpg', 'rust'),
 ('95245ac6495adceb.jpg', 'rust'),
 ('e03795d3f908a31d.jpg', 'rust'),
 ('c2b1aa975047d7f0.jpg', 'rust'),
 ('8f2acfec7cc230c1.jpg', 'rust'),
 ('8dea32f7b03b5121.jpg', 'rust'),
 ('93fce6b50df12a01.jpg', 'rust'),
 ('a1c2faea525554f1.jpg', 'rust'),
 ('8f20be1ad23cd725.jpg', 'rust'),
 ('91f0af891fa147ac.jpg', 'rust'),
 ('d6e2ce215d9a05f2.jpg', 'rust'),
 ('847b34450db547d7.jpg', 'rust'),
 ('d292fc82ed4172e6.jpg', 'rust'),
 ('9a9f2e6003cb976c.jpg', 'rust'),
 ('e48fc33896394739.jpg', 'rust'),
 ('b9dd8aa81d2c3437.jpg', 'rust'),
 ('fa900bfc9dc701aa.jpg', 'rust'),
 ('cd9233e52ae427a6.jpg', 'rust'),
 ('bf22f63ed33ac010.jpg', 'rust'),
 ('ddb839dd4d25108b.jpg', 'rust'),
 ('e9f1cc9ba00772b8.jpg', 'rust'),
 ('c4c54fcb5b5705a4.jpg', 'rust'),
 ('99c9c9269b3e6c34.jpg', 'rust'),
 ('8c95b34ad893ab59.jpg', 'rust'),
 ('c494d8c73614e6be.jpg', 'rust'),
 ('d794c3f8988572c3.jpg', 'rust'),
 ('a88895d7943f6a63.jpg', 'rust'),
 ('edf585af80c8aa0e.jpg', 'rust'),
 ('91a43f43e27dc383.jpg', 'rust'),
 ('a9de962c33346a9a.jpg', 'rust'),
 ('a30283ff461df30e.jpg', 'rust'),
 ('9190539a6b0bbd3d.jpg', 'rust'),
 ('80abc9d697ec22b6.jpg', 'rust'),
 ('f15a8c9a3aa5526d.jpg', 'rust'),
 ('aab865829f3dd215.jpg', 'rust'),
 ('da3d82601e653afc.jpg', 'rust'),
 ('b7e5c8c04cf9b928.jpg', 'rust'),
 ('d61236da9659d538.jpg', 'rust'),
 ('a1874e8c18f95be3.jpg', 'rust'),
 ('88b3f86bc843d58d.jpg', 'rust'),
 ('c8ac5765870bb2ba.jpg', 'rust'),
 ('fb943c40cbd8742e.jpg', 'rust'),
 ('eae4a50e164e73f0.jpg', 'rust'),
 ('d28d8dc9a45a63ea.jpg', 'rust'),
 ('e4374bc1b64b59a2.jpg', 'rust'),
 ('febcd48148e92f11.jpg', 'rust'),
 ('a4d081e9c38775bb.jpg', 'rust'),
 ('a1e9d79ceabc1061.jpg', 'rust'),
 ('cde2df213f02d306.jpg', 'rust'),
 ('e89772b7d28a944a.jpg', 'rust'),
 ('ebfe5005f9071c0d.jpg', 'rust'),
 ('8faa21bead40b563.jpg', 'rust'),
 ('c58039da54edd6a5.jpg', 'rust'),
 ('cfd07ae01b61b346.jpg', 'rust'),
 ('bc43d0289bf09fe8.jpg', 'rust'),
 ('bd9ed078c3620a37.jpg', 'rust'),
 ('a18e9b0d487664f7.jpg', 'rust'),
 ('f56ccb8641ce1665.jpg', 'rust'),
 ('f4d0eac9a3f408ea.jpg', 'rust'),
 ('f149428d9f479a47.jpg', 'rust'),
 ('ffeef07b00c1f080.jpg', 'rust'),
 ('90b2cbcf9a7c4538.jpg', 'rust'),
 ('b646ce9fce191321.jpg', 'rust'),
 ('cfb8e0b68362db03.jpg', 'rust'),
 ('fd6b1950658d03da.jpg', 'rust'),
 ('b56ad726c8529c8b.jpg', 'rust'),
 ('f4cb48a4eec6ec90.jpg', 'rust'),
 ('83b32ea384bf9634.jpg', 'rust'),
 ('fa96105d4969ab78.jpg', 'rust'),
 ('df92f89611b41f41.jpg', 'rust'),
 ('a55bd2f2c5f02d81.jpg', 'rust'),
 ('de0dd7608d6ea2d0.jpg', 'rust'),
 ('d1403d7382ab1fb6.jpg', 'rust'),
 ('b450c27ade59ab2c.jpg', 'rust'),
 ('a9b116c36b47e307.jpg', 'rust'),
 ('d837d922d813e969.jpg', 'rust'),
 ('fce8f0211fe01ed8.jpg', 'rust'),
 ('f00d97ec8a62c7e2.jpg', 'rust'),
 ('bfad3f1403a20b17.jpg', 'rust'),
 ('a84b95bc1a526d4f.jpg', 'rust'),
 ('fc08ca3f4b160fc6.jpg', 'rust'),
 ('b42b80b74faa34cb.jpg', 'rust'),
 ('b801305b6a656fe7.jpg', 'rust'),
 ('df6070b067766662.jpg', 'rust'),
 ('c4c11d3cfc3248f7.jpg', 'rust'),
 ('b7628746264daacd.jpg', 'rust'),
 ('9569383f433a6f41.jpg', 'rust'),
 ('e38f9438127e19cb.jpg', 'rust'),
 ('c26d93f4c2c3aaca.jpg', 'rust'),
 ('c00e2335f69f1aba.jpg', 'rust'),
 ('ab29d1b5859a17d4.jpg', 'rust'),
 ('cb8660f0e5958fa6.jpg', 'rust'),
 ('ec83c7c04a1e9db9.jpg', 'rust'),
 ('858ade6ea27592b8.jpg', 'rust'),
 ('ca361fce6abe00cc.jpg', 'rust'),
 ('d20a299a3dc5d7d4.jpg', 'rust'),
 ('b297b43d650f6cc0.jpg', 'rust'),
 ('aa94964aaa4df52d.jpg', 'rust'),
 ('99c367875e18b24b.jpg', 'rust'),
 ('bac0dac7d82585b6.jpg', 'rust'),
 ('8a86d49f916a2b6d.jpg', 'rust'),
 ('fde5c0c3d2175225.jpg', 'rust'),
 ('97c0d31d3c343b36.jpg', 'rust'),
 ('afc080cf5b3d79a0.jpg', 'rust'),
 ('c7453b8f41351be2.jpg', 'rust'),
 ('8e79802b3fb770c8.jpg', 'rust'),
 ('8cda9ee9800b9f1d.jpg', 'rust'),
 ('ad1cd41cda17cc17.jpg', 'rust'),
 ('dbc07f3f8020d4b3.jpg', 'rust'),
 ('e02b9a39cd663cca.jpg', 'rust'),
 ('f9c08ed8e03d90af.jpg', 'rust'),
 ('aa03b7a84ebd4995.jpg', 'rust'),
 ('ff909c85e83f20e4.jpg', 'rust'),
 ('df570928d3d22a9a.jpg', 'rust'),
 ('aae5d9b65da04368.jpg', 'rust'),
 ('ea54939ac84fd88e.jpg', 'rust'),
 ('92a409c0d6fe7a6d.jpg', 'rust'),
 ('baacd8f0f29a7061.jpg', 'rust'),
 ('f2c8c94c2d313ee3.jpg', 'rust'),
 ('b528e8c28edbd29a.jpg', 'rust'),
 ('a5cda58d45ce54cc.jpg', 'rust'),
 ('ffa09c786f43c052.jpg', 'rust'),
 ('f89bc8e4ccc289c7.jpg', 'rust'),
 ('e18c947f337964a1.jpg', 'rust'),
 ('ec550ef05ea109de.jpg', 'rust'),
 ('f03393cc310f9fb0.jpg', 'rust'),
 ('afcf958fcaca0109.jpg', 'rust'),
 ('a381e182876f3dd6.jpg', 'rust'),
 ('bd05f0ca41c93d6b.jpg', 'rust'),
 ('e5e6d2dc9d0a0b51.jpg', 'rust'),
 ('cfab6e1e20b690b1.jpg', 'rust'),
 ('f9b4649d1d5414b5.jpg', 'rust'),
 ('da0775fd870855b0.jpg', 'rust'),
 ('fce8963918c1629f.jpg', 'rust'),
 ('e9d60ce0dcef450a.jpg', 'rust'),
 ('8afab5369497d092.jpg', 'rust'),
 ('e733cc3cdca143c1.jpg', 'rust'),
 ('e5b0969bdad9c908.jpg', 'rust'),
 ('c6be6222e3f183e2.jpg', 'rust'),
 ('a5591a2a71b541ef.jpg', 'rust'),
 ('c1b439c235eb8e47.jpg', 'rust'),
 ('aab6d606c32f013f.jpg', 'rust'),
 ('de74de64cb60c11c.jpg', 'rust'),
 ('c382ed64c07dfea0.jpg', 'rust'),
 ('b4e1c0fdc749de08.jpg', 'rust'),
 ('c4dad3b3b4852867.jpg', 'rust'),
 ('af5c1f91f272284a.jpg', 'rust'),
 ('aa9a946c4c23f3f1.jpg', 'rust'),
 ('cad871996e4b78a2.jpg', 'rust'),
 ('d0973e720f60e11f.jpg', 'rust'),
 ('e03755ce56e4acb0.jpg', 'rust'),
 ('f43876d5914d6919.jpg', 'rust'),
 ('85a5c4dd5ed2b868.jpg', 'rust'),
 ('c2f6b6d0cad22a2b.jpg', 'rust'),
 ('aa94d28a93559fb8.jpg', 'rust'),
 ('e19791d01e683d3d.jpg', 'rust'),
 ('f876d91631747223.jpg', 'rust'),
 ('8cf89cc586331e37.jpg', 'rust'),
 ('db308de738148677.jpg', 'rust'),
 ('efe1c2fb8100d88f.jpg', 'rust'),
 ('8499edfce222e1e1.jpg', 'rust'),
 ('c9eda1909292b3de.jpg', 'rust'),
 ('c0e0f81e9f1eaf03.jpg', 'rust'),
 ('8bd39bca890ced49.jpg', 'rust'),
 ('8daa52da8897ea4b.jpg', 'rust'),
 ('b09f8ac1e68a6772.jpg', 'rust'),
 ('b6cbe7adc2c4888a.jpg', 'rust'),
 ('fdd608e58907e3e0.jpg', 'rust'),
 ('dce08ccc7c003f6f.jpg', 'rust'),
 ('a8f09383dcaf6307.jpg', 'rust'),
 ('fae7c0a28d2218ef.jpg', 'rust'),
 ('bc90b50b928fe88f.jpg', 'rust'),
 ('e54b34ad63c253a5.jpg', 'rust'),
 ('d7c166745629459e.jpg', 'rust'),
 ('fac2c5ed0eac3072.jpg', 'rust'),
 ('8568b2e313eefc12.jpg', 'rust'),
 ('c56316977a3d7508.jpg', 'rust'),
 ('83e7f58c947c4728.jpg', 'rust'),
 ('832f7e641ec74474.jpg', 'rust'),
 ('d58dd660231f545b.jpg', 'rust'),
 ('a846cdcad8f1472e.jpg', 'rust'),
 ('888e5642ce65f771.jpg', 'rust'),
 ('ebc315dc4c6a2d29.jpg', 'rust'),
 ('cec684eed5252a1d.jpg', 'rust'),
 ('d7826acca9bcb862.jpg', 'rust'),
 ('ab95ea9dea9e8108.jpg', 'rust'),
 ('8797679517649d22.jpg', 'rust'),
 ('d448d5b4cab7185d.jpg', 'rust'),
 ('b463427db0d461cf.jpg', 'rust'),
 ('828f375d5e5843c9.jpg', 'rust'),
 ('bdfb41d1f9a28070.jpg', 'rust'),
 ('a8e1bc575f2b0155.jpg', 'rust'),
 ('90d1d0cdf52c16ed.jpg', 'rust'),
 ('c03f47d51a54eae8.jpg', 'rust'),
 ('9d903bbbc06c25e9.jpg', 'rust'),
 ('ee07d048ff181ab9.jpg', 'rust'),
 ('de9f2428345d705e.jpg', 'rust'),
 ('cae937c030a1f86f.jpg', 'rust'),
 ('87c32387a2b4eaea.jpg', 'rust'),
 ('b485b2cc560db5b5.jpg', 'rust'),
 ('909ed2fd8e0cba07.jpg', 'rust'),
 ('fa4785678cd02cda.jpg', 'rust'),
 ('e5dec29796d01558.jpg', 'rust'),
 ('c4cf8f8aec981c4b.jpg', 'rust'),
 ('c8232d72e49307df.jpg', 'rust'),
 ('cd4f26bf83cc2093.jpg', 'rust'),
 ('e8d9c3275a389a6a.jpg', 'rust'),
 ('d4a18a9efcbe3124.jpg', 'rust'),
 ('cdf43ac5238c53b8.jpg', 'rust'),
 ('d29f01cd9db24c35.jpg', 'rust'),
 ('aff0cab9cf303411.jpg', 'rust'),
 ('ce4eee02f46242b7.jpg', 'rust'),
 ('a4313e914fd60ba7.jpg', 'rust'),
 ('e856f6229f492b0d.jpg', 'rust'),
 ('ed93a0fa560e6531.jpg', 'rust'),
 ('e58ac3949f81d39c.jpg', 'rust'),
 ('b4a6c316dd5f4858.jpg', 'rust'),
 ('b1cd46ad561551f4.jpg', 'rust'),
 ('d9a0b69d88d7c2e4.jpg', 'rust'),
 ('b38aa9e091776d25.jpg', 'rust'),
 ('e0cb3f081fbe65a0.jpg', 'rust'),
 ('d0f45e8c6c4b4c8f.jpg', 'rust'),
 ('9deb1b81c42b4576.jpg', 'rust'),
 ('f5db2874139c47c1.jpg', 'rust'),
 ('fb9287c0b18aa5ec.jpg', 'rust'),
 ('a03f973bda0f0361.jpg', 'rust'),
 ('e90e1acab7e5aa50.jpg', 'rust'),
 ('9fa089cb938bc175.jpg', 'rust'),
 ('d2896219cffd0e51.jpg', 'rust'),
 ('c8c60ceeec4a46f5.jpg', 'rust'),
 ('c0a020df9b3eded8.jpg', 'rust'),
 ('b9da42646c795965.jpg', 'rust'),
 ('b76dc38da481b4a5.jpg', 'rust'),
 ('e5a59fcbcb890838.jpg', 'rust'),
 ('b1a5929298ef0dcd.jpg', 'rust'),
 ('c76328952d9e7d90.jpg', 'rust'),
 ('839b918b7ced00fc.jpg', 'rust'),
 ('c82933c21f623f9b.jpg', 'rust'),
 ('ad32d2d3c98da94a.jpg', 'rust'),
 ('83e3d2329933c5f2.jpg', 'rust'),
 ('fc020e0de1bab8d7.jpg', 'rust'),
 ('de4527f46f18388c.jpg', 'rust'),
 ('8a1f1cdc4f283d33.jpg', 'rust'),
 ('81a8f5d54427c87f.jpg', 'rust'),
 ('c5ee6a66eca4425c.jpg', 'rust'),
 ('b63fc9cc688ee2c0.jpg', 'rust'),
 ('dede8434053bb2c9.jpg', 'rust'),
 ('c58c8bc03ec362fd.jpg', 'rust'),
 ('fc3887612a7f3198.jpg', 'rust'),
 ('abe5e19c981cb8c9.jpg', 'rust'),
 ('d3f77b6121cb0909.jpg', 'rust'),
 ('908f6b209dcf136d.jpg', 'rust'),
 ('e1c9978286961be7.jpg', 'rust'),
 ('d46896409cefab9a.jpg', 'rust'),
 ('87a5489f1e4dc3d2.jpg', 'rust'),
 ('fc6080faa73839ab.jpg', 'rust'),
 ('f865cc9c1d66c136.jpg', 'rust'),
 ('a387e73e38353c50.jpg', 'rust'),
 ('d0bafa5844f4338e.jpg', 'rust'),
 ('bee6c10382e4d7a9.jpg', 'rust'),
 ('81c8d2be1abfaa92.jpg', 'rust'),
 ('c934cccb174cc93b.jpg', 'rust'),
 ('f0eb97c70a9e8988.jpg', 'rust'),
 ('c0bc431f5396b0f5.jpg', 'rust'),
 ('e9ea40bd83949d9a.jpg', 'rust'),
 ('a4c14bbbf066c89b.jpg', 'rust'),
 ('a53fa25fc4e60c34.jpg', 'rust'),
 ('ad99cf603bac421e.jpg', 'rust'),
 ('dfc0328c3876e1f1.jpg', 'rust'),
 ('fd3b585e83219925.jpg', 'rust'),
 ('fd619276c81a7c1a.jpg', 'rust'),
 ('b4d55ea6709a97c0.jpg', 'rust'),
 ('a7e613159fb22859.jpg', 'rust'),
 ('fca495f43f00e499.jpg', 'rust'),
 ('ab5e828e1bcf2887.jpg', 'rust'),
 ('b6c0c8eda5e4c6e8.jpg', 'rust'),
 ('936f6194f11e835a.jpg', 'rust'),
 ('b2e3c7d3028db1ac.jpg', 'rust'),
 ('fb0e92b59637a124.jpg', 'rust'),
 ('fead8b83cb6a2490.jpg', 'rust'),
 ('bfac94a7f0b60b02.jpg', 'rust'),
 ('8fbd27b078a0b0d5.jpg', 'rust'),
 ('a0e0c3f71d0738de.jpg', 'rust'),
 ('d2cbcc4732b9ce06.jpg', 'rust'),
 ('a4b17595b24a5a2f.jpg', 'rust'),
 ('d6e447ca1f967842.jpg', 'rust'),
 ('a696b130bd6e8f03.jpg', 'rust'),
 ('f98b90de67360564.jpg', 'rust'),
 ('ca303681f18ff8ae.jpg', 'rust'),
 ('ca4835dc6de52372.jpg', 'rust'),
 ('cddd20c43963ce2e.jpg', 'rust'),
 ('ba91c21fc735a3e0.jpg', 'rust'),
 ('efa9c7dc6b002155.jpg', 'rust'),
 ('d5d81484865b2f3f.jpg', 'rust'),
 ('beb542f99608d2ac.jpg', 'rust'),
 ('a5b2a059695d7655.jpg', 'rust'),
 ('b4f6baa004a0767f.jpg', 'rust'),
 ('8ddaa5a5caa5caa8.jpg', 'rust'),
 ('cd99c5888b342de7.jpg', 'rust'),
 ('b49fc924c77138ca.jpg', 'rust'),
 ('e0c0d55eceecc26c.jpg', 'rust'),
 ('dca525ea879c4a99.jpg', 'rust'),
 ('bda08481484afffd.jpg', 'rust'),
 ('aaecf21252830bfb.jpg', 'rust'),
 ('a57abed01897c916.jpg', 'rust'),
 ('b3bff7c0215c9188.jpg', 'rust'),
 ('cf80b25fe0dcd4b0.jpg', 'rust'),
 ('94ccde9c16ba2723.jpg', 'rust'),
 ('df7492c2c4333387.jpg', 'rust'),
 ('882d092f9f76f9a0.jpg', 'rust'),
 ('a8bd55b203daa0de.jpg', 'rust'),
 ('c9e9c4669bb30876.jpg', 'rust'),
 ('8a7ad65bd849d505.jpg', 'rust'),
 ('dc9174bd07b482ea.jpg', 'rust'),
 ('a8e02cf4970ebf0d.jpg', 'rust'),
 ('c58717e8256d2a76.jpg', 'rust'),
 ('abc397970c5a3c68.jpg', 'rust'),
 ('b0d9c859ec2936ba.jpg', 'rust'),
 ('f2dc41a1fccb6486.jpg', 'rust'),
 ('aad535b55192a59a.jpg', 'rust'),
 ('f09697d6dada8805.jpg', 'rust'),
 ('a17c9256abb7350a.jpg', 'rust'),
 ('d783907d695c7548.jpg', 'rust'),
 ('fc90c7f580cd856c.jpg', 'rust'),
 ('c5e81ed58bad891c.jpg', 'rust'),
 ('8c7c1ff199813c74.jpg', 'rust'),
 ('d8eeca049f688ed4.jpg', 'rust'),
 ('a0260ff0da9f525d.jpg', 'rust'),
 ('cf0ec556d852a29e.jpg', 'rust'),
 ('fdb4128a44fef031.jpg', 'rust'),
 ('e59ed2dc91b002bb.jpg', 'rust'),
 ('c0bcda4f1c8067f3.jpg', 'rust'),
 ('92a91fd0b485fa9a.jpg', 'rust'),
 ('c933888f37b9b813.jpg', 'rust'),
 ('f8b4d13b0bc179c1.jpg', 'rust'),
 ('d36cc3c8c9e22ca7.jpg', 'rust'),
 ('f53c3194f8c390cb.jpg', 'rust'),
 ('cfb8cec59888173c.jpg', 'rust'),
 ('d2622eb73198ab9c.jpg', 'rust'),
 ('c93a61ca82c27afe.jpg', 'rust'),
 ('e78a9512b151b9cb.jpg', 'rust'),
 ('acdedc4a08655877.jpg', 'rust'),
 ('efcaa02dd705c172.jpg', 'rust'),
 ('fa63c3ea8d285c54.jpg', 'rust'),
 ('953f3074707063b7.jpg', 'rust'),
 ('bcd69ee03a352d14.jpg', 'rust'),
 ('bcfd90636aa2658a.jpg', 'rust'),
 ('d5e72937db898007.jpg', 'rust'),
 ('a5eeb294c45f2827.jpg', 'rust'),
 ('fd10c2cf9b72a324.jpg', 'rust'),
 ('df1b49c511ebb105.jpg', 'rust'),
 ('cfaab2997580eea0.jpg', 'rust'),
 ('acb91a1a6065afb6.jpg', 'rust'),
 ('90f7e0c35d5a1f14.jpg', 'rust'),
 ('ced36b93c8c498c3.jpg', 'rust'),
 ('f1a3071c3ba9a78a.jpg', 'rust'),
 ('d4a96a051ba46d5f.jpg', 'rust'),
 ('839b6a7a21adaf14.jpg', 'rust'),
 ('c0630f69dcd1789d.jpg', 'rust'),
 ('fcddc0c2c79bc2c0.jpg', 'rust'),
 ('c2ccaf86b8d9549a.jpg', 'rust'),
 ('b71d2ed1226a2d53.jpg', 'rust'),
 ('f4e68b8e34f1b818.jpg', 'rust'),
 ('e9e8b8f8e2e8a944.jpg', 'rust'),
 ('ce469d3c40997ccb.jpg', 'rust'),
 ('b421cc5b670f2397.jpg', 'rust'),
 ('83d43f4e7470c2f1.jpg', 'rust'),
 ('fe87a28b94b4945a.jpg', 'rust'),
 ('a9e0d38b1cacf4c9.jpg', 'rust'),
 ('fa7eaa508162952f.jpg', 'rust'),
 ('dfb8688819856be9.jpg', 'rust'),
 ('d08fc33fe44a57c0.jpg', 'rust'),
 ('d0a1009ea59f6fd6.jpg', 'rust'),
 ('c44d7e3338199d71.jpg', 'rust'),
 ('f103543332de1e75.jpg', 'rust'),
 ('fc11c63989f089f9.jpg', 'rust'),
 ('9ef22a56e70c8ad2.jpg', 'rust'),
 ('c1b3a11c7c6d9e0e.jpg', 'rust'),
 ('fff8e3b8c1d88300.jpg', 'rust'),
 ('9db072e315821ebd.jpg', 'rust'),
 ('bdb29857980a4bb6.jpg', 'rust'),
 ('e6a21cb69da821bb.jpg', 'rust'),

In [6]:
submission = pd.DataFrame(subm, columns= ['image', 'labels'])
submission.set_index('image', inplace = True)
submission.to_csv('./submission.csv')

In [7]:
submited = pd.read_csv('./submission.csv')
submited

                     image labels
0     df98c83c4d383c2d.jpg   rust
1     817e97dad0c33ae0.jpg   rust
2     e984c49aef3d54a1.jpg   rust
3     8cf2ee38c423d837.jpg   rust
4     e5319c4b1ce90d5e.jpg   rust
...                    ...    ...
3723  903f6578bc0b8fc8.jpg   rust
3724  a076da6fa6ca06e4.jpg   rust
3725  eebe02cc97709d21.jpg   rust
3726  d4a430cc663792fe.jpg   rust
3727  f1bb28fee48284c3.jpg   rust

[3728 rows x 2 columns]