In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load
from copy import deepcopy
import json
import os

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.experimental import enable_hist_gradient_boosting
from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.multioutput import MultiOutputRegressor
from sklearn.preprocessing import LabelEncoder

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory


#for dirname, _, filenames in os.walk('/kaggle/input'):
#    for filename in filenames:
#        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/usr/local/lib/python3.11/dist-packages/sklearn/experimental/enable_hist_gradient_boosting.py:16: UserWarning: Since version 1.0, it is not needed to import enable_hist_gradient_boosting anymore. HistGradientBoostingClassifier and HistGradientBoostingRegressor are now stable and can be normally imported from sklearn.ensemble.
  warnings.warn(

In [2]:
data_train = [json.loads(line) for line in open('../input/stanford-covid-vaccine/train.json','r')]
data_test = [json.loads(linha) for linha in open('../input/stanford-covid-vaccine/test.json','r')]
test_set = pd.read_csv('../input/stanford-covid-vaccine/sample_submission.csv')

In [3]:
for jason in data_train:
    jason['step'] = list(range(jason['seq_scored']))
    jason['sequence'] = list(jason['sequence'])
    jason['structure'] = list(jason['structure'])
    jason['predicted_loop_type'] = list(jason['predicted_loop_type'])

In [4]:
for jason in data_test:
    jason['step'] = list(range(jason['seq_scored']))
    jason['sequence'] = list(jason['sequence'])
    jason['structure'] = list(jason['structure'])
    jason['predicted_loop_type'] = list(jason['predicted_loop_type'])

In [5]:
train = pd.json_normalize(data = data_train, 
                            record_path ='reactivity',  
                            meta =['id','signal_to_noise',
                                  'SN_filter','seq_length','seq_scored']) 
train.rename(columns={0:'reactivity'}, inplace=True)
train['step'] = pd.json_normalize(data = data_train, 
                            record_path ='step'
                                        )
train['sequence'] = pd.json_normalize(data = data_train, 
                            record_path ='sequence'
                                        )
train['structure'] = pd.json_normalize(data = data_train, 
                            record_path ='structure'
                                        )
train['predicted_loop_type'] = pd.json_normalize(data = data_train, 
                            record_path ='predicted_loop_type'
                                        )
train['reactivity_error'] = pd.json_normalize(data = data_train, 
                            record_path ='reactivity_error'
                                        )
train['deg_Mg_pH10'] = pd.json_normalize(data = data_train, 
                            record_path ='deg_Mg_pH10'
                                        )
train['deg_error_Mg_pH10'] = pd.json_normalize(data = data_train, 
                            record_path ='deg_error_Mg_pH10'
                                        )
train['deg_pH10'] = pd.json_normalize(data = data_train, 
                            record_path ='deg_pH10',
                                        )
train['deg_error_pH10'] = pd.json_normalize(data = data_train, 
                            record_path ='deg_error_pH10',
                                        )
train['deg_Mg_50C'] = pd.json_normalize(data = data_train, 
                            record_path ='deg_Mg_50C',
                                        )
train['deg_error_Mg_50C'] = pd.json_normalize(data = data_train, 
                            record_path ='deg_error_Mg_50C',
                                        )
train['deg_50C'] = pd.json_normalize(data = data_train, 
                            record_path ='deg_50C',
                                        )
train['deg_error_50C'] = pd.json_normalize(data = data_train, 
                            record_path ='deg_error_50C',
                                        )

train.set_index(['id','step'], inplace=True)

In [6]:
test = pd.json_normalize(data = data_test,
                         record_path = 'sequence',
                        meta = ['id','seq_length','seq_scored'])
test.rename(columns={0:'sequence'},inplace=True)
test['step'] = pd.json_normalize(data = data_test,
                                record_path = 'step')
test['sequence'] = pd.json_normalize(data = data_test,
                                    record_path = 'sequence')
test['structure'] = pd.json_normalize(data = data_test,
                                     record_path = 'structure')
test['predicted_loop_type'] = pd.json_normalize(data = data_test,
                                               record_path = 'predicted_loop_type')
test.set_index(['id','step'], inplace=True)

In [7]:
train

                   reactivity signal_to_noise SN_filter seq_length seq_scored  \
id           step
id_001f94081 0         0.3297           6.894         1        107         68
             1         1.5693           6.894         1        107         68
             2         1.1227           6.894         1        107         68
             3         0.8686           6.894         1        107         68
             4         0.7217           6.894         1        107         68
...                       ...             ...       ...        ...        ...
id_fff546103 63        0.0272           6.545         1        107         68
             64        0.0382           6.545         1        107         68
             65        0.0381           6.545         1        107         68
             66       -0.0066           6.545         1        107         68
             67        0.0706           6.545         1        107         68

                  sequence structure predicted_loop_type  reactivity_error  \
id           step
id_001f94081 0           G         .                   E            0.1359
             1           G         .                   E            0.2070
             2           A         .                   E            0.1633
             3           A         .                   E            0.1452
             4           A         .                   E            0.1314
...                    ...       ...                 ...               ...
id_fff546103 63          A         (                   S            0.0267
             64          A         (                   S            0.0219
             65          G         (                   S            0.0218
             66          G         (                   S            0.0220
             67          U         .                   H            0.0287

                   deg_Mg_pH10  deg_error_Mg_pH10  deg_pH10  deg_error_pH10  \
id           step
id_001f94081 0          0.7556             0.2613    2.3375          0.2631
             1          2.9830             0.3842    3.5060          0.2860
             2          0.2526             0.1372    0.3008          0.0964
             3          1.3789             0.2531    1.0108          0.1574
             4          0.6376             0.1798    0.2635          0.1000
...                        ...                ...       ...             ...
id_fff546103 63         0.5059             0.0626    0.4998          0.0996
             64         0.2025             0.0411    0.3057          0.0760
             65         0.1827             0.0391    0.1642          0.0611
             66         0.3261             0.0509    0.1654          0.0719
             67         0.4529             0.0565    0.4840          0.0936

                   deg_Mg_50C  deg_error_Mg_50C  deg_50C  deg_error_50C
id           step
id_001f94081 0         0.3581            0.1501   0.6382         0.2167
             1         2.9683            0.2750   3.4773         0.3475
             2         0.2589            0.0947   0.9988         0.1880
             3         1.4552            0.1866   1.3228         0.2124
             4         0.7244            0.1369   0.7877         0.1703
...                       ...               ...      ...            ...
id_fff546103 63        0.2870            0.0638   0.1820         0.0809
             64        0.2022            0.0520   0.2038         0.0748
             65        0.2047            0.0520   0.1120         0.0612
             66        0.2447            0.0595   0.1186         0.0723
             67        0.1802            0.0515   0.3013         0.0892

[146880 rows x 17 columns]

In [8]:
test

                  sequence seq_length seq_scored structure predicted_loop_type
id           step
id_00b436dec 0.0         G        107         68         .                   E
             1.0         G        107         68         .                   E
             2.0         A        107         68         .                   E
             3.0         A        107         68         .                   E
             4.0         A        107         68         .                   E
...                    ...        ...        ...       ...                 ...
id_ff103a85c NaN         A        107         68         .                   E
             NaN         C        107         68         .                   E
             NaN         A        107         68         .                   E
             NaN         A        107         68         .                   E
             NaN         C        107         68         .                   E

[25680 rows x 5 columns]

In [9]:
np.random.seed(2020) #Seed the randomness to be deterministic

In [10]:
enc = LabelEncoder()
category_cols_train = [cols for cols in train.columns if train[cols].dtype == 'object']
category_cols_test = [cols for cols in test.columns if test[cols].dtype == 'object']
print(category_cols_train)
print(category_cols_test)
X_train_enc = deepcopy(train)
X_test_enc = deepcopy(test)
for cols in category_cols_train:
    X_train_enc[cols] = enc.fit_transform(X_train_enc[cols])
for cols in category_cols_test:
    X_test_enc[cols] = enc.fit_transform(X_test_enc[cols])

['signal_to_noise', 'SN_filter', 'seq_length', 'seq_scored', 'sequence', 'structure', 'predicted_loop_type']
['sequence', 'seq_length', 'seq_scored', 'structure', 'predicted_loop_type']

In [11]:
X = X_train_enc.drop(['reactivity', 'deg_Mg_pH10', 'deg_pH10', 'deg_Mg_50C', 'deg_50C'],axis=1)
y = X_train_enc.loc[:,['reactivity', 'deg_Mg_pH10', 'deg_pH10', 'deg_Mg_50C', 'deg_50C']]

In [12]:
hgbr = MultiOutputRegressor(HistGradientBoostingRegressor(max_iter=1000,early_stopping=True,n_iter_no_change=10,
                                     learning_rate=0.0025,tol=1e-5,verbose=2)
                           ,n_jobs = 4)

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [14]:
X_train

,,signal_to_noise,SN_filter,seq_length,seq_scored,sequence,structure,predicted_loop_type,reactivity_error,deg_error_Mg_pH10,deg_error_pH10,deg_error_Mg_50C,deg_error_50C
id,step,,,,,,,,,,,,
id_6cb65a015,15,1562,0,0,0,0,2,2,0.0703,0.0547,0.0898,0.0490,0.0979
id_4d9e01b6c,51,968,1,0,0,2,2,2,0.0269,0.0504,0.0757,0.0366,0.0552
id_b726b998a,59,1561,1,0,0,1,0,5,0.0322,0.0324,0.0443,0.0255,0.0454
id_6add5e119,55,1140,1,0,0,1,1,5,0.0470,0.0582,0.1067,0.0645,0.1071
id_f32da8012,50,216,0,0,0,1,2,1,0.1142,0.1826,0.2554,0.1391,0.2900
...,...,...,...,...,...,...,...,...,...,...,...,...,...
id_a875d91d3,32,841,1,0,0,0,2,1,0.0864,0.1232,0.1559,0.0974,0.1783
id_219d8c69a,47,1660,1,0,0,0,2,2,0.0236,0.0207,0.0419,0.0267,0.0431
id_1f465a329,27,1505,1,0,0,0,2,2,0.0365,0.1212,0.1199,0.0986,0.0989
id_c7e70795c,50,105,0,0,0,3,1,5,0.5741,0.2186,0.8641,0.4461,0.7169
id_47ecb057c,4,923,0,0,0,1,2,1,0.1500,0.1097,0.1542,0.1298,0.1578

In [15]:
hgbr.fit(X_train,y_train)

Binning 0.010 GB of training data: Binning 0.010 GB of training data: Binning 0.010 GB of training data: Binning 0.010 GB of training data: 0.132 s
Binning 0.001 GB of validation data: 0.134 s
Binning 0.001 GB of validation data: 0.005 s
Fitting gradient boosted rounds:
[1/1000] 0.005 s
Fitting gradient boosted rounds:
[1/1000] 0.125 s
Binning 0.001 GB of validation data: 0.005 s
Fitting gradient boosted rounds:
[1/1000] 1 tree, 31 leaves, max depth = 14, train loss: 0.86483, val loss: 0.84308, in 0.010s
[2/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.28187, val loss: 0.29610, in 0.011s
[2/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.40364, val loss: 0.29568, in 0.011s
[2/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.86436, val loss: 0.84265, in 0.010s
[3/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.28158, val loss: 0.29583, in 0.011s
[3/1000] 1 tree, 31 leaves, max depth = 14, train loss: 0.86388, val loss: 0.84225, in 0.009s
[4/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.40332, val loss: 0.29538, in 0.011s
[3/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.28129, val loss: 0.29557, in 0.011s
[4/1000] 1 tree, 31 leaves, max depth = 14, train loss: 0.86340, val loss: 0.84186, in 0.009s
[5/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.40299, val loss: 0.29509, in 0.011s
[4/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.28101, val loss: 0.29531, in 0.011s
[5/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.86294, val loss: 0.84143, in 0.010s
[6/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.40267, val loss: 0.29479, in 0.011s
[5/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.28072, val loss: 0.29505, in 0.011s
[6/1000] 1 tree, 31 leaves, max depth = 14, train loss: 0.86247, val loss: 0.84104, in 0.010s
[7/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.40235, val loss: 0.29449, in 0.011s
[6/1000] 1 tree, 31 leaves, max depth = 9, train loss: 0.28045, val loss: 0.29479, in 0.011s
[7/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.86201, val loss: 0.84060, in 0.010s
[8/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.40203, val loss: 0.29420, in 0.011s
[7/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.28017, val loss: 0.29454, in 0.011s
[8/1000] 1 tree, 31 leaves, max depth = 14, train loss: 0.86154, val loss: 0.84022, in 0.011s
[9/1000] 0.132 s
Binning 0.001 GB of validation data: 1 tree, 31 leaves, max depth = 10, train loss: 0.40171, val loss: 0.29391, in 0.011s
[8/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.27988, val loss: 0.29429, in 0.011s
[9/1000] 0.005 s
Fitting gradient boosted rounds:
[1/1000] 1 tree, 31 leaves, max depth = 14, train loss: 0.86108, val loss: 0.83984, in 0.010s
[10/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.40139, val loss: 0.29362, in 0.011s
[9/1000] 1 tree, 31 leaves, max depth = 9, train loss: 0.27961, val loss: 0.29403, in 0.011s
[10/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.86063, val loss: 0.83941, in 0.009s
[11/1000] 1 tree, 31 leaves, max depth = 9, train loss: 0.25175, val loss: 0.27870, in 0.011s
[2/1000] 1 tree, 31 leaves, max depth = 13, train loss: 0.86017, val loss: 0.83902, in 0.009s
[12/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.40108, val loss: 0.29333, in 0.011s
[10/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.27933, val loss: 0.29378, in 0.011s
[11/1000] 1 tree, 31 leaves, max depth = 9, train loss: 0.25148, val loss: 0.27841, in 0.011s
[3/1000] 1 tree, 31 leaves, max depth = 14, train loss: 0.85971, val loss: 0.83865, in 0.010s
[13/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.27906, val loss: 0.29353, in 0.011s
[12/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.40077, val loss: 0.29304, in 0.011s
[11/1000] 1 tree, 31 leaves, max depth = 9, train loss: 0.25121, val loss: 0.27812, in 0.011s
[4/1000] 1 tree, 31 leaves, max depth = 14, train loss: 0.85926, val loss: 0.83827, in 0.009s
[14/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.27878, val loss: 0.29328, in 0.011s
[13/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.40045, val loss: 0.29275, in 0.011s
[12/1000] 1 tree, 31 leaves, max depth = 9, train loss: 0.25094, val loss: 0.27783, in 0.011s
[5/1000] 1 tree, 31 leaves, max depth = 14, train loss: 0.85880, val loss: 0.83790, in 0.010s
[15/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.27851, val loss: 0.29303, in 0.011s
[14/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.40014, val loss: 0.29246, in 0.011s
[13/1000] 1 tree, 31 leaves, max depth = 9, train loss: 0.25067, val loss: 0.27754, in 0.011s
[6/1000] 1 tree, 31 leaves, max depth = 13, train loss: 0.85835, val loss: 0.83752, in 0.009s
[16/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.27823, val loss: 0.29279, in 0.011s
[15/1000] 1 tree, 31 leaves, max depth = 9, train loss: 0.25041, val loss: 0.27726, in 0.011s
[7/1000] 1 tree, 31 leaves, max depth = 13, train loss: 0.85790, val loss: 0.83715, in 0.009s
[17/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.39983, val loss: 0.29218, in 0.015s
[14/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.27796, val loss: 0.29254, in 0.011s
[16/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.25014, val loss: 0.27697, in 0.011s
[8/1000] 1 tree, 31 leaves, max depth = 13, train loss: 0.85746, val loss: 0.83678, in 0.009s
[18/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.39952, val loss: 0.29189, in 0.013s
[15/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.27769, val loss: 0.29230, in 0.011s
[17/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.24988, val loss: 0.27668, in 0.011s
[9/1000] 1 tree, 31 leaves, max depth = 13, train loss: 0.85701, val loss: 0.83641, in 0.009s
[19/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.39922, val loss: 0.29161, in 0.012s
[16/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.27743, val loss: 0.29206, in 0.011s
[18/1000] 1 tree, 31 leaves, max depth = 13, train loss: 0.85657, val loss: 0.83604, in 0.009s
[20/1000] 1 tree, 31 leaves, max depth = 9, train loss: 0.24962, val loss: 0.27640, in 0.011s
[10/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.39891, val loss: 0.29133, in 0.011s
[17/1000] 1 tree, 31 leaves, max depth = 13, train loss: 0.85613, val loss: 0.83568, in 0.009s
[21/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.27716, val loss: 0.29182, in 0.011s
[19/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.24936, val loss: 0.27612, in 0.010s
[11/1000] 1 tree, 31 leaves, max depth = 13, train loss: 0.85569, val loss: 0.83531, in 0.009s
[22/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.39861, val loss: 0.29105, in 0.011s
[18/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.27689, val loss: 0.29158, in 0.010s
[20/1000] 1 tree, 31 leaves, max depth = 9, train loss: 0.24910, val loss: 0.27584, in 0.010s
[12/1000] 1 tree, 31 leaves, max depth = 13, train loss: 0.85526, val loss: 0.83495, in 0.009s
[23/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.39831, val loss: 0.29077, in 0.011s
[19/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.27663, val loss: 0.29134, in 0.011s
[21/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.24884, val loss: 0.27556, in 0.010s
[13/1000] 1 tree, 31 leaves, max depth = 13, train loss: 0.85483, val loss: 0.83460, in 0.009s
[24/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.27636, val loss: 0.29110, in 0.010s
[22/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.39799, val loss: 0.29049, in 0.011s
[20/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.24858, val loss: 0.27528, in 0.011s
[14/1000] 1 tree, 31 leaves, max depth = 13, train loss: 0.85440, val loss: 0.83424, in 0.009s
[25/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.27610, val loss: 0.29088, in 0.010s
[23/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.39769, val loss: 0.29021, in 0.011s
[21/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.24833, val loss: 0.27500, in 0.010s
[15/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.85398, val loss: 0.83385, in 0.010s
[26/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.27584, val loss: 0.29065, in 0.011s
[24/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.39737, val loss: 0.28995, in 0.011s
[22/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.24807, val loss: 0.27472, in 0.010s
[16/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.85357, val loss: 0.83349, in 0.010s
[27/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.27558, val loss: 0.29043, in 0.010s
[25/1000] 1 tree, 31 leaves, max depth = 9, train loss: 0.24782, val loss: 0.27445, in 0.010s
[17/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.39707, val loss: 0.28967, in 0.011s
[23/1000] 1 tree, 31 leaves, max depth = 14, train loss: 0.85314, val loss: 0.83314, in 0.009s
[28/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.27532, val loss: 0.29020, in 0.010s
[26/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.24757, val loss: 0.27417, in 0.011s
[18/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.39678, val loss: 0.28939, in 0.011s
[24/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.85273, val loss: 0.83276, in 0.011s
[29/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.27506, val loss: 0.28998, in 0.011s
[27/1000] 1 tree, 31 leaves, max depth = 9, train loss: 0.24731, val loss: 0.27391, in 0.011s
[19/1000] 1 tree, 31 leaves, max depth = 14, train loss: 0.85231, val loss: 0.83241, in 0.009s
[30/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.39648, val loss: 0.28912, in 0.011s
[25/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.27480, val loss: 0.28975, in 0.011s
[28/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.85190, val loss: 0.83205, in 0.010s
[31/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.24706, val loss: 0.27363, in 0.011s
[20/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.39619, val loss: 0.28885, in 0.011s
[26/1000] 1 tree, 31 leaves, max depth = 14, train loss: 0.85148, val loss: 0.83171, in 0.009s
[32/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.27455, val loss: 0.28953, in 0.010s
[29/1000] 1 tree, 31 leaves, max depth = 9, train loss: 0.24681, val loss: 0.27337, in 0.011s
[21/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.39590, val loss: 0.28858, in 0.011s
[27/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.85108, val loss: 0.83135, in 0.010s
[33/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.27429, val loss: 0.28930, in 0.011s
[30/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.24656, val loss: 0.27309, in 0.011s
[22/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.39560, val loss: 0.28831, in 0.011s
[28/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.85067, val loss: 0.83097, in 0.010s
[34/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.27404, val loss: 0.28909, in 0.011s
[31/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.24632, val loss: 0.27283, in 0.011s
[23/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.39530, val loss: 0.28805, in 0.011s
[29/1000] 1 tree, 31 leaves, max depth = 12, train loss: 0.85026, val loss: 0.83059, in 0.010s
[35/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.27378, val loss: 0.28886, in 0.011s
[32/1000] 1 tree, 31 leaves, max depth = 9, train loss: 0.24608, val loss: 0.27258, in 0.011s
[24/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.39500, val loss: 0.28778, in 0.012s
[30/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.84987, val loss: 0.83023, in 0.010s
[36/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.27353, val loss: 0.28865, in 0.012s
[33/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.24583, val loss: 0.27232, in 0.011s
[25/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.84947, val loss: 0.82986, in 0.010s
[37/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.39471, val loss: 0.28751, in 0.011s
[31/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.27328, val loss: 0.28842, in 0.011s
[34/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.24559, val loss: 0.27206, in 0.011s
[26/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.84908, val loss: 0.82950, in 0.011s
[38/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.39442, val loss: 0.28725, in 0.012s
[32/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.27303, val loss: 0.28821, in 0.011s
[35/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.24535, val loss: 0.27180, in 0.011s
[27/1000] 1 tree, 31 leaves, max depth = 12, train loss: 0.84867, val loss: 0.82915, in 0.010s
[39/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.39414, val loss: 0.28698, in 0.012s
[33/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.27278, val loss: 0.28799, in 0.011s
[36/1000] 1 tree, 31 leaves, max depth = 9, train loss: 0.24511, val loss: 0.27154, in 0.011s
[28/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.84828, val loss: 0.82878, in 0.009s
[40/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.39385, val loss: 0.28672, in 0.011s
[34/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.27253, val loss: 0.28778, in 0.011s
[37/1000] 1 tree, 31 leaves, max depth = 12, train loss: 0.84786, val loss: 0.82841, in 0.010s
[41/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.24487, val loss: 0.27128, in 0.011s
[29/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.39357, val loss: 0.28646, in 0.011s
[35/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.27229, val loss: 0.28756, in 0.011s
[38/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.84747, val loss: 0.82805, in 0.010s
[42/1000] 1 tree, 31 leaves, max depth = 9, train loss: 0.24463, val loss: 0.27102, in 0.010s
[30/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.39329, val loss: 0.28620, in 0.011s
[36/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.27204, val loss: 0.28735, in 0.011s
[39/1000] 1 tree, 31 leaves, max depth = 12, train loss: 0.84707, val loss: 0.82768, in 0.010s
[43/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.24439, val loss: 0.27077, in 0.011s
[31/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.39301, val loss: 0.28594, in 0.012s
[37/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.84667, val loss: 0.82732, in 0.010s
[44/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.27180, val loss: 0.28713, in 0.011s
[40/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.24415, val loss: 0.27051, in 0.011s
[32/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.84627, val loss: 0.82696, in 0.011s
[45/1000] 1 tree, 31 leaves, max depth = 12, train loss: 0.27155, val loss: 0.28693, in 0.011s
[41/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.39273, val loss: 0.28568, in 0.012s
[38/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.24392, val loss: 0.27025, in 0.011s
[33/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.84589, val loss: 0.82661, in 0.010s
[46/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.27131, val loss: 0.28671, in 0.011s
[42/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.39245, val loss: 0.28543, in 0.012s
[39/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.24368, val loss: 0.27000, in 0.011s
[34/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.84549, val loss: 0.82624, in 0.010s
[47/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.27107, val loss: 0.28651, in 0.012s
[43/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.39218, val loss: 0.28517, in 0.011s
[40/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.24345, val loss: 0.26974, in 0.011s
[35/1000] 1 tree, 31 leaves, max depth = 13, train loss: 0.84510, val loss: 0.82592, in 0.010s
[48/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.27083, val loss: 0.28629, in 0.011s
[44/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.39190, val loss: 0.28491, in 0.011s
[41/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.24321, val loss: 0.26950, in 0.011s
[36/1000] 1 tree, 31 leaves, max depth = 15, train loss: 0.84470, val loss: 0.82556, in 0.011s
[49/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.27059, val loss: 0.28609, in 0.012s
[45/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.39162, val loss: 0.28466, in 0.012s
[42/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.24298, val loss: 0.26925, in 0.011s
[37/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.84430, val loss: 0.82520, in 0.010s
[50/1000] 1 tree, 31 leaves, max depth = 12, train loss: 0.27035, val loss: 0.28588, in 0.011s
[46/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.39135, val loss: 0.28442, in 0.012s
[43/1000] 1 tree, 31 leaves, max depth = 9, train loss: 0.24275, val loss: 0.26901, in 0.011s
[38/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.84392, val loss: 0.82486, in 0.010s
[51/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.27011, val loss: 0.28567, in 0.011s
[47/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.39108, val loss: 0.28416, in 0.012s
[44/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.24252, val loss: 0.26875, in 0.011s
[39/1000] 1 tree, 31 leaves, max depth = 15, train loss: 0.84352, val loss: 0.82451, in 0.010s
[52/1000] 1 tree, 31 leaves, max depth = 12, train loss: 0.26988, val loss: 0.28546, in 0.011s
[48/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.39081, val loss: 0.28391, in 0.011s
[45/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.84315, val loss: 0.82416, in 0.011s
[53/1000] 1 tree, 31 leaves, max depth = 7, train loss: 0.24229, val loss: 0.26851, in 0.011s
[40/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.26964, val loss: 0.28525, in 0.011s
[49/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.39054, val loss: 0.28367, in 0.011s
[46/1000] 1 tree, 31 leaves, max depth = 7, train loss: 0.24207, val loss: 0.26828, in 0.011s
[41/1000] 1 tree, 31 leaves, max depth = 13, train loss: 0.84275, val loss: 0.82380, in 0.011s
[54/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.26941, val loss: 0.28504, in 0.011s
[50/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.39027, val loss: 0.28342, in 0.011s
[47/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.24184, val loss: 0.26802, in 0.011s
[42/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.84237, val loss: 0.82344, in 0.011s
[55/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.26917, val loss: 0.28484, in 0.011s
[51/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.39001, val loss: 0.28318, in 0.011s
[48/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.84200, val loss: 0.82310, in 0.010s
[56/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.24161, val loss: 0.26778, in 0.012s
[43/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.38974, val loss: 0.28293, in 0.011s
[49/1000] 1 tree, 31 leaves, max depth = 14, train loss: 0.84160, val loss: 0.82274, in 0.010s
[57/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.26894, val loss: 0.28464, in 0.012s
[52/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.24138, val loss: 0.26754, in 0.012s
[44/1000] 1 tree, 31 leaves, max depth = 14, train loss: 0.84122, val loss: 0.82244, in 0.009s
[58/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.38948, val loss: 0.28270, in 0.011s
[50/1000] 1 tree, 31 leaves, max depth = 12, train loss: 0.26871, val loss: 0.28444, in 0.011s
[53/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.24116, val loss: 0.26730, in 0.011s
[45/1000] 1 tree, 31 leaves, max depth = 10, train loss: 0.84084, val loss: 0.82209, in 0.010s
[59/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.38920, val loss: 0.28246, in 0.011s
[51/1000] 1 tree, 31 leaves, max depth = 11, train loss: 0.26849, val loss: 0.28423, in 0.011s

MultiOutputRegressor(estimator=HistGradientBoostingRegressor(early_stopping=True,
                                                             learning_rate=0.0025,
                                                             max_iter=1000,
                                                             tol=1e-05,
                                                             verbose=2),
                     n_jobs=4)

In [16]:
y_pred = hgbr.predict(X_test)

In [17]:
print(mean_squared_error(y_test,y_pred,squared=False))

0.9527754952037544

In [18]:
X_train_enc[X_test_enc.columns]

                   sequence  seq_length  seq_scored  structure  \
id           step
id_001f94081 0            2           0           0          2
             1            2           0           0          2
             2            0           0           0          2
             3            0           0           0          2
             4            0           0           0          2
...                     ...         ...         ...        ...
id_fff546103 63           0           0           0          0
             64           0           0           0          0
             65           2           0           0          0
             66           2           0           0          0
             67           3           0           0          2

                   predicted_loop_type
id           step
id_001f94081 0                       1
             1                       1
             2                       1
             3                       1
             4                       1
...                                ...
id_fff546103 63                      5
             64                      5
             65                      5
             66                      5
             67                      2

[146880 rows x 5 columns]

In [19]:
hgbr.fit(X_train_enc[X_test_enc.columns],y)

1 tree, 31 leaves, max depth = 17, train loss: 0.30569, val loss: 0.21854, in 0.010s
Fit 1000 trees in 10.544 s, (31000 total leaves)
Time spent computing histograms: 5.519s
Time spent finding best splits:  0.471s
Time spent applying splits:      2.599s
Time spent predicting:           0.215s
Binning 0.005 GB of training data: 1 tree, 31 leaves, max depth = 12, train loss: 0.20791, val loss: 0.22916, in 0.010s
Fit 1000 trees in 11.958 s, (31000 total leaves)
Time spent computing histograms: 6.169s
Time spent finding best splits:  0.575s
Time spent applying splits:      3.021s
Time spent predicting:           0.235s
Binning 0.005 GB of training data: 1 tree, 31 leaves, max depth = 12, train loss: 0.17990, val loss: 0.20408, in 0.009s
Fit 1000 trees in 10.642 s, (31000 total leaves)
Time spent computing histograms: 5.558s
Time spent finding best splits:  0.492s
Time spent applying splits:      2.656s
Time spent predicting:           0.217s
Binning 0.005 GB of training data: 1 tree, 31 leaves, max depth = 11, train loss: 0.50927, val loss: 0.77906, in 0.009s
Fit 1000 trees in 9.244 s, (31000 total leaves)
Time spent computing histograms: 4.865s
Time spent finding best splits:  0.398s
Time spent applying splits:      2.362s
Time spent predicting:           0.143s
Binning 0.005 GB of training data: 0.026 s
Binning 0.001 GB of validation data: 0.001 s
Fitting gradient boosted rounds:
[1/1000] 1 tree, 31 leaves, max depth = 9, train loss: 0.27708, val loss: 0.32237, in 0.011s
[2/1000] 0.028 s
Binning 0.001 GB of validation data: 0.001 s
Fitting gradient boosted rounds:
[1/1000] 0.034 s
Binning 0.001 GB of validation data: 0.001 s
Fitting gradient boosted rounds:
[1/1000] 1 tree, 31 leaves, max depth = 9, train loss: 0.27708, val loss: 0.32237, in 0.012s
[3/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.25879, val loss: 0.28062, in 0.011s
[2/1000] 0.046 s
Binning 0.001 GB of validation data: 0.001 s
Fitting gradient boosted rounds:
[1/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.86446, val loss: 1.22964, in 0.012s
[2/1000] 1 tree, 31 leaves, max depth = 9, train loss: 0.27708, val loss: 0.32237, in 0.012s
[4/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.25879, val loss: 0.28062, in 0.011s
[3/1000] 1 tree, 31 leaves, max depth = 9, train loss: 0.40437, val loss: 0.41700, in 0.011s
[2/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.86445, val loss: 1.22964, in 0.012s
[3/1000] 1 tree, 31 leaves, max depth = 9, train loss: 0.27708, val loss: 0.32237, in 0.011s
[5/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.25879, val loss: 0.28062, in 0.011s
[4/1000] 1 tree, 31 leaves, max depth = 9, train loss: 0.40437, val loss: 0.41700, in 0.011s
[3/1000] 1 tree, 31 leaves, max depth = 9, train loss: 0.27708, val loss: 0.32237, in 0.011s
[6/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.25879, val loss: 0.28062, in 0.011s
[5/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.86445, val loss: 1.22964, in 0.012s
[4/1000] 1 tree, 31 leaves, max depth = 9, train loss: 0.40437, val loss: 0.41700, in 0.011s
[4/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.25879, val loss: 0.28062, in 0.011s
[6/1000] 1 tree, 31 leaves, max depth = 9, train loss: 0.27708, val loss: 0.32237, in 0.012s
[7/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.86445, val loss: 1.22964, in 0.012s
[5/1000] 1 tree, 31 leaves, max depth = 9, train loss: 0.40437, val loss: 0.41700, in 0.011s
[5/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.25879, val loss: 0.28062, in 0.011s
[7/1000] 1 tree, 31 leaves, max depth = 9, train loss: 0.27708, val loss: 0.32237, in 0.011s
[8/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.86445, val loss: 1.22964, in 0.012s
[6/1000] 1 tree, 31 leaves, max depth = 9, train loss: 0.40437, val loss: 0.41700, in 0.011s
[6/1000] 1 tree, 31 leaves, max depth = 9, train loss: 0.27708, val loss: 0.32237, in 0.011s
[9/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.25879, val loss: 0.28062, in 0.011s
[8/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.86445, val loss: 1.22964, in 0.012s
[7/1000] 1 tree, 31 leaves, max depth = 9, train loss: 0.40437, val loss: 0.41700, in 0.011s
[7/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.25879, val loss: 0.28062, in 0.011s
[9/1000] 1 tree, 31 leaves, max depth = 9, train loss: 0.27708, val loss: 0.32237, in 0.011s
[10/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.86445, val loss: 1.22964, in 0.012s
[8/1000] 1 tree, 31 leaves, max depth = 9, train loss: 0.40437, val loss: 0.41700, in 0.011s
[8/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.25879, val loss: 0.28062, in 0.011s
[10/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.86445, val loss: 1.22964, in 0.012s
[9/1000] 1 tree, 31 leaves, max depth = 9, train loss: 0.40437, val loss: 0.41700, in 0.011s
[9/1000] 1 tree, 31 leaves, max depth = 9, train loss: 0.40437, val loss: 0.41700, in 0.012s
[10/1000] 1 tree, 31 leaves, max depth = 8, train loss: 0.86445, val loss: 1.22964, in 0.012s
[10/1000] 1 tree, 31 leaves, max depth = 9, train loss: 0.27708, val loss: 0.32237, in 0.011s
Fit 10 trees in 0.157 s, (310 total leaves)
Time spent computing histograms: 0.047s
Time spent finding best splits:  0.002s
Time spent applying splits:      0.040s
Time spent predicting:           0.003s
Binning 0.005 GB of training data: 0.036 s
Binning 0.001 GB of validation data: 0.001 s
Fitting gradient boosted rounds:
[1/1000] 1 tree, 31 leaves, max depth = 7, train loss: 0.70178, val loss: 0.58457, in 0.011s
[2/1000] 1 tree, 31 leaves, max depth = 7, train loss: 0.70178, val loss: 0.58457, in 0.011s
[3/1000] 1 tree, 31 leaves, max depth = 7, train loss: 0.70178, val loss: 0.58457, in 0.011s
[4/1000] 1 tree, 31 leaves, max depth = 7, train loss: 0.70178, val loss: 0.58457, in 0.011s
[5/1000] 1 tree, 31 leaves, max depth = 7, train loss: 0.70178, val loss: 0.58457, in 0.011s
[6/1000] 1 tree, 31 leaves, max depth = 7, train loss: 0.70178, val loss: 0.58457, in 0.011s
[7/1000] 1 tree, 31 leaves, max depth = 7, train loss: 0.70178, val loss: 0.58457, in 0.011s
[8/1000] 1 tree, 31 leaves, max depth = 7, train loss: 0.70178, val loss: 0.58457, in 0.011s
[9/1000] 1 tree, 31 leaves, max depth = 7, train loss: 0.70178, val loss: 0.58457, in 0.011s
[10/1000]

MultiOutputRegressor(estimator=HistGradientBoostingRegressor(early_stopping=True,
                                                             learning_rate=0.0025,
                                                             max_iter=1000,
                                                             tol=1e-05,
                                                             verbose=2),
                     n_jobs=4)

In [20]:
y_pred_2 = hgbr.predict(X_test_enc)

In [21]:
y_pred_2.shape

(25680, 5)

In [22]:
submission = pd.DataFrame(np.concatenate([test_set.id_seqpos.values[:,np.newaxis],y_pred_2],axis=1),columns=test_set.columns)
submission.head(10)
submission.to_csv('submission.csv',index=False)